# -*- coding: utf-8 -*-
"""earth.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1htQfoYrMGXCwqjUVhwznqskAu5Hqi1pc
"""

from google.colab import files
uploaded = files.upload()

# Commented out IPython magic to ensure Python compatibility.
import io
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

# %matplotlib inline
!pip install astral
import datetime
from astral import LocationInfo
from astral.sun import sun
import pytz

data = pd.read_csv(io.BytesIO(uploaded['earthquakes.csv']))

data['time'] = pd.to_datetime(data.time)
pst = pytz.timezone('US/Pacific')


def is_daylight(x):
  loc = LocationInfo(latitude=x.latitude, longitude=x.longitude, timezone='US/Pacific')
  #loc = LocationInfo(36.7, -121.2, timezone='US/Pacific')
  
  
  shakedate = x.time.date() 
  sunup = sun(loc.observer, date=shakedate)['sunrise']
  sundown = sun(loc.observer, date=shakedate)['sunset']
  
  
  if sunup.astimezone(pst).time() < x.time.time() < sundown.astimezone(pst).time(): 
     return 'yes'
  else:
    return'no'

data['daylight'] = data.apply(is_daylight, axis=1)

plt.rcParams['figure.figsize']=(35,9)
plt.style.use('fast')
sns.countplot(data['mag'] )
plt.title('Mags of Earthquakes', fontweight=30, fontsize=20)
plt.xticks(rotation = 90)
plt.show()

print(plt.style.available)

time = pd.to_datetime(data.time)

data['time'] = pd.to_datetime(data.time)

plt.rcParams['figure.figsize']=(15,8)


sns.countplot(data['time'].dt.hour)
plt.title('earthquakes in hours')
plt.show()

data['round_mag']=round(data['mag'])
data.head()

max_mag = [data[data['time'].dt.hour == i].mag.max() for i in data.time.dt.hour]

sns.scatterplot(data.time.dt.hour, max_mag, hue=data.daylight)
plt.title('Max mag for each hour')
plt.xlabel('time')
plt.ylabel('max mag')
plt.show()

df=pd.crosstab(data.time.dt.hour, data['round_mag'])
df.div(df.sum(1).astype(float), axis = 0).plot.bar(stacked=True)
plt.xticks(rotation=90)
plt.show()

data.round_mag.plot(kind='hist')

sns.set_style('white')
sns.heatmap(data.corr(), annot=True, cmap='coolwarm')

#categorical plot
sns.swarmplot(x=data['magType'],
              y=data['mag'], hue=data.daylight)

data.daylight.value_counts()

import folium
folium.Map(location=[37.7, -122.4], width=700, height=700)

